name: minesweeper
env_kwargs:
    board_height: 10
    board_width: 10
    num_mines: 10

network:
    board_embed_dim: 4
    board_conv_channels: [8, 16]
    board_kernel_shape: 3
    num_mines_embed_dim: 4
    final_layer_dims: [16, 8]

training:
    num_epochs: 100
    num_learner_steps_per_epoch: 500
    n_steps: 10
    total_batch_size: 128
    total_num_eval: 500

a2c:
    normalize_advantage: False
    discount_factor: 0.99
    bootstrapping_factor: 0.95
    l_pg: 1.0
    l_td: 1.0
    l_en: 0.01
    learning_rate: 1e-4
