name: snake
env_kwargs:
    num_rows: 12
    num_cols: 12
    time_limit: 4000

network:
    num_channels: 32
    policy_layers: [64, 64]
    value_layers: [128, 128]

training:
    num_epochs: 100
    num_learner_steps_per_epoch: 500
    n_steps: 20
    total_batch_size: 128

evaluation:
    eval_total_batch_size: 200
    greedy_eval_total_batch_size: 200

a2c:
    normalize_advantage: False
    discount_factor: 0.997
    bootstrapping_factor: 0.95
    l_pg: 1.0
    l_td: 1.0
    l_en: 0.01
    learning_rate: 4e-4
