site_name: Jumanji docs
site_description: Documentation for Jumanji
site_author: InstaDeep Developers
site_url: https://instadeep.gitlab.io/mkdocs
site_dir: public
repo_name: instadeep/jumanji
repo_url: https://gitlab.com/instadeep/templates/machine-learning-project

strict: false # Don't allow warnings during the build process
dev_addr: '0.0.0.0:8000' # generate a warning when running in a docker container

theme:
  name: material
  language: en
  palette:
    primary: light blue
    accent: indigo
  logo: PATH_TO_LOGO
  favicon: PATH_TO_FAVICON
  icon:
    repo: fontawesome/brands/gitlab
  font:
    text: Avenir Next
  features:
    - navigation.tracking

markdown_extensions:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      emoji_index: !!python/name:pymdownx.emoji.gemoji
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - def_list

plugins:
  - search
  - git-revision-date
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
          selection:
            filters:
              - '!^test'
  - include-markdown

nav:
  - Home: index.md
  - API Reference:
      - jax:
          - environments:
              - snake: api/jax/environments/snake.md
              - swap: api/jax/environments/swap.md
              - pcb_grid: api/jax/environments/pcb_grid.md
              - connect4: api/jax/environments/connect4.md
              - knapsack: api/jax/environments/knapsack.md
              - tsp: api/jax/environments/tsp.md
          - jax_env: api/jax/env.md
          - types: api/jax/types.md
          - wrappers: api/jax/wrappers.md
      - validation:
          - agents:
              - random_agent: api/validation/agents/random_agent.md
          - benchmark_loops:
              - deep_mind_env_benchmark_loop: api/validation/benchmark_loops/deep_mind_env_benchmark_loop.md
              - jax_env_benchmark_loop: api/validation/benchmark_loops/jax_env_benchmark_loop.md
          - environment_loops:
              - jax_environment_loop: api/validation/environment_loops/jax_environment_loop.md
