name: minesweeper
env_kwargs:
    board_height: 10
    board_width: 10
    num_mines: 10

network:
    board_embed_dim: 4
    board_conv_channels: [8, 16]
    board_kernel_shape: 3
    num_mines_embed_dim: 4
    final_layer_dims: [16, 8]
