defaults:
    - _self_
    - env: rubiks_cube  # [binpack, cvrp, game2048, jobshop, knapsack, maze, minesweeper, routing, rubiks_cube, snake, tsp]

agent: random  # [random, a2c]

seed: 0

logger:
    type: terminal  # [neptune, tensorboard, terminal]
    save_checkpoint: false  # [false, true]
    name: ${agent}_${env.name}
