defaults:
    - _self_
    - agent: random  # [random, a2c]
    - environment: rubiks_cube  # [binpack, cvrp, knapsack, jobshop, routing, rubiks_cube, minesweeper, snake, tsp]

seed: 0
num_epochs: 100
num_learner_steps_per_epoch: 500
total_num_eval: 500

n_steps: 10
total_batch_size: 128

logger:
    type: terminal  # [neptune, tensorboard, terminal]
    name: ${agent.name}_${environment.name}
