defaults:
    - _self_
    - env: rubiks_cube  # [binpack, cvrp, knapsack, jobshop, routing, rubiks_cube, minesweeper, snake, tsp, game2048]

agent: random  # [random, a2c]

seed: 0

logger:
    type: terminal  # [neptune, tensorboard, terminal]
    name: ${agent}_${env.name}
