defaults:
    - _self_
    - env: snake  # [binpack, cvrp, game2048, jobshop, knapsack, maze, minesweeper, rubiks_cube, snake, tsp, connector]

agent: a2c  # [random, a2c]

seed: 0

logger:
    type: neptune  # [neptune, tensorboard, terminal]
    save_checkpoint: true  # [false, true]
    name: ${agent}_${env.name}_gamma_0.997_lr_4e-4_n_steps_20
