defaults:
  - environment: snake
  - environment_loop: jax_jit_seq

num_env_steps: null
num_episodes: 10
print_time: True
print_time_in_ms: True

# Move output dir creation to tmp
hydra:
  run:
    dir: /tmp
